Feat statistics
johannschwabe/AirspaceAuctionSimulator pull request #35
Opened 2022-08-30 12:34 UTC by thommann

2022-08-31 11:27 UTC, johannschwabe commented on Simulator/Simulator.py
> +        if len(new_agents) > 0 or self.mechanism.allocator.wants_to_reallocate():
pass environment

2022-08-31 11:27 UTC, johannschwabe commented on Simulator/Simulator.py
> +        if len(new_agents) > 0 or self.mechanism.allocator.wants_to_reallocate():
and tick

2022-08-31 11:31 UTC, johannschwabe commented on Simulator/Statistics/Statistics.py
> +    L2_DISTANCE_TRAVELED = "l2_distance_traveled"
same as L1

2022-09-09 09:21 UTC, johannschwabe commented on API/API.py
> +
assure compatibility with CLI

2022-09-09 13:06 UTC, joelbarmettlerUZH commented
lgtm

2022-09-09 13:12 UTC, johannschwabe requested changes
some smoll considerations

2022-09-09 13:12 UTC, johannschwabe commented on Development/playground.py
> +    return EnvironmentGen(map_dimensions, [MapTile([15, 17161, 11475], area)], 50, 10).generate()
needs new arguments

2022-09-09 13:12 UTC, johannschwabe commented on Simulator/AStar/AStar.py
> +        colliding_agents = self.environment.intersect_path_coordinate(position, agent)
naming chaos: var name colliding_agents is already taken

2022-09-09 13:12 UTC, johannschwabe commented on Simulator/Environment/Environment.py
> +            allocation_period = dimension.t
doesn't make sense to allocate agents in the last tick

2022-09-09 13:12 UTC, johannschwabe commented on Simulator/Environment/Environment.py
>      def register_agent(self, agent: "Agent", time_step: int):
no longer just registering agents, new name needed

2022-09-09 13:12 UTC, johannschwabe commented on Simulator/IO/Statistics.py
> +                assert isinstance(intersecting_space_segment, SpaceSegment)
Should selfcollisions be counted?

2022-09-09 13:12 UTC, johannschwabe commented on Simulator/IO/Statistics.py
> +                    if isinstance(intersecting_agent, PathAgent):
self intersections

2022-09-09 13:12 UTC, johannschwabe commented on Visualizer/src/API/api.js
> +async function openDB() {
maybe move db helper to seperate file?

2022-09-09 13:44 UTC, joelbarmettlerUZH approved these changes
lgtm, minor stuff

2022-09-09 13:44 UTC, joelbarmettlerUZH commented on CLI.py
> +                    metavar="[300, 1000]",
```suggestion
parser.add_argument('--allocation-period', dest="allocationPeriod", type=int, choices=range(300, 4000),
                    metavar="[300, 4000]",
```

2022-09-09 13:44 UTC, joelbarmettlerUZH commented on Simulator/IO/Statistics.py
> +    def path_segment_statistics(path_segment: "PathSegment"):
indicate return type "PathStatistics"

2022-09-09 13:44 UTC, joelbarmettlerUZH commented on Simulator/IO/Statistics.py
> +    def space_segment_statistics(space_segment: "SpaceSegment"):
indicate return type "SpaceSegmentStatistics"

2022-09-09 14:14 UTC, johannschwabe approved these changes

2022-09-09 16:23 UTC, johannschwabe approved these changes

2022-09-09 16:23 UTC, merged